DeshanSLIIT/Models/Asset.cs
using Fingers10.ExcelExport.Attributes;
using System.ComponentModel.DataAnnotations;

namespace DeshanSLIIT.Models
{
    public class Asset
    {
        [Key]
        [IncludeInReport(Order = 1)]
        public int Id { get; set; }
        [Required]
        [IncludeInReport(Order = 2)]
        public string Name { get; set; }
        [Required]
        [IncludeInReport(Order = 3)]
        public string ISBN { get; set; }
    }
}

DeshanSLIIT/Models/Cart.cs
using System.ComponentModel.DataAnnotations;

namespace DeshanSLIIT.Models
{
    public class Cart
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int AssetID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string ISBN { get; set; }
    }
}

DeshanSLIIT/Models/Transfer.cs
using System.ComponentModel.DataAnnotations;

namespace DeshanSLIIT.Models
{
    public class Transfer
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int TID { get; set; }
        [Required]
        public int CartID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string ISBN { get; set; }
        [Required]
        public string Location { get; set; }
        [Required]
        public string Category { get; set; }
        [Required]
        public DateTime Date { get; set; } = DateTime.Now;
    }
}

DeshanSLIIT/Controllers/AssetController.cs
using DeshanSLIIT.Models;
using Fingers10.ExcelExport.ActionResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DeshanSLIIT.Controllers
{
    public class AssetController : Controller
    {
        private readonly AppDatabaseContexts _database;
        public AssetController(AppDatabaseContexts database)
        {
            _database = database;
        }
        public IActionResult Index()
        {
            IEnumerable<Asset> data = _database.Assets.ToList();
            return View(data);
        }

        public IActionResult Cart()
        {
            IEnumerable<Cart> data = _database.Carts.ToList();
            return View(data);
        }

        public IActionResult TransferTable()
        {
            IEnumerable<Transfer> data = _database.Transfers.ToList();
            List<Transfer> result = new List<Transfer>();
            foreach (var transfer in data)
            {
                var cat = _database.Categories.Find(Convert.ToInt32(transfer.Category));
                transfer.Category = cat.CategoryType;
                result.Add(transfer);
            }
            return View(result);
        }

        public IActionResult TransferTableByID(int? id)
        {
            IEnumerable<Transfer> data = _database.Transfers.Where(r => r.TID == id).ToList();
            return View(data);
        }

        public IActionResult SetToCart(int? id)
        {
            var data = _database.Assets.Find(id);
            var obj = new Cart();
            obj.AssetID = data.Id;
            obj.Name = data.Name;
            obj.ISBN = data.ISBN;
            _database.Carts.Add(obj);
            _database.SaveChanges();
            return RedirectToAction("Index");
        }

        //Oparation
        public IActionResult TransferAssets(TransferDetails td)
        {
            IEnumerable<Cart> Cartobj = _database.Carts.ToList();
            if (Cartobj == null)
            {
                return NotFound();
            }

            int nextTID = MaxTID();
            foreach (var item in Cartobj)
            {
                int tempID = item.Id;
                var data = new Transfer();
                data.TID = nextTID;
                data.CartID = item.Id;
                data.Name = item.Name;
                data.ISBN = item.ISBN;
                data.Location = td.Location;
                data.Category = td.CatData.CategoryType;
                _database.Transfers.Add(data);
                _database.SaveChanges();
                Delete(tempID);
            }
            return RedirectToAction("Index");
        }

        //Oparation
        public IActionResult TransferAction()
        {
            List<Category> categories = _database.Categories.ToList();
            ViewBag.CategoryList = new SelectList(categories, "Id", "CategoryType");
            return View();
        }

        public void Delete(int? id)
        {
            var obj = _database.Carts.Find(id);
            _database.Carts.Remove(obj);
            _database.SaveChanges();
        }

        public int MaxTID()
        {
            var maxId = (_database.Transfers.Select(q => (int?)q.TID).Max() ?? 0) + 1;
            return maxId;
        }

        public IActionResult DownloadExcel()
        {
            IEnumerable<Asset> data = _database.Assets.ToList();
            List<Asset> temp = new List<Asset>();
            foreach (Asset item in data)
            {
                temp.Add(new Asset
                {
                    Id = item.Id,
                    Name = item.Name,
                    ISBN = item.ISBN,
                });
            }
            return new ExcelResult<Asset>(temp, "Sheet1", "AssetReport");
        }
    }
}

DeshanSLIIT/Controllers/AuthController.cs
using DeshanSLIIT.Models;
using Microsoft.AspNetCore.Mvc;

namespace DeshanSLIIT.Controllers
{
    public class AuthController : Controller
    {
        private readonly AppDatabaseContexts _database;
        public AuthController(AppDatabaseContexts database)
        {
            _database = database;
        }

        public IActionResult Index(Auth obj)
        {
            var user = _database.Auths.FirstOrDefault(x => x.Email == obj.Email && x.Password == obj.Password);
            HttpContext.Session.SetString("name", user.Name);
            if(user == null)
            {
                return View("Index");
            }
            else
            {
                ViewData["Message"] = HttpContext.Session.GetString("name");
                return View("Index1");
            }
        }

        public IActionResult Login()
        {
            return View("Index");
        }

    }
}

DeshanSLIIT/Controllers/TestController.cs
using DeshanSLIIT.Models;
using Microsoft.AspNetCore.Mvc;

namespace DeshanSLIIT.Controllers
{
    public class TestController : Controller
    {
        private readonly AppDatabaseContexts _database;
        public TestController(AppDatabaseContexts database)
        {
            _database = database;
        }

        public IActionResult Index()
        {
            IEnumerable<Test> test = _database.Tests.ToList();
            return View(test);
        }
    }
}

DeshanSLIIT/Views/Asset/Cart.cshtml
@model IEnumerable<Cart>
@{
    ViewData["Title"] = "Cart";
}

<h1>Cart</h1>

<a type="button" class="btn btn-primary" asp-controller="Asset" asp-action="Index">Index</a>
&nbsp;
<a type="button" class="btn btn-primary" asp-controller="Asset" asp-action="TransferTable">Transfer Table</a>
<p></p>
<h1>SetToCart</h1>

<table class="table table-success table-hover">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">AssetID</th>
          <th scope="col">Name</th>
          <th scope="col">ISBN</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
          <th scope="row">@data.Id</th>
          <td>@data.AssetID</td>
          <td>@data.Name</td>
          <td>@data.ISBN</td>
        </tr>
        }
    </tbody>
</table>

@if (Model != null && Model.Count() != 0)
{
   <a type="button" class="btn btn-primary" asp-controller="Asset" asp-action="TransferAction">Transfer</a>
}

DeshanSLIIT/Views/Asset/Index.cshtml
@model IEnumerable<Asset>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<a type="button" class="btn btn-primary" asp-controller="Asset" asp-action="Cart">Cart</a> 
&nbsp;
<a type="button" class="btn btn-primary" asp-controller="Asset" asp-action="TransferTable">Transfer Table</a>
&nbsp;
<a type="button" class="btn btn-primary" asp-controller="Auth" asp-action="Login">Login</a>
&nbsp;
<a type="button" class="btn btn-warning" asp-controller="Test" asp-action="Index">Test</a>
&nbsp;
<a class="btn btn-secondary" href="@Url.Action("DownloadExcel", "Asset")">Download</a>
<p></p>

<table class="table table-success table-hover">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">ISBN</th>
          <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
              <th scope="row">@data.Id</th>
              <td>@data.Name</td>
              <td>@data.ISBN</td>
              <td><a type="button" class="btn btn-primary" asp-controller="Asset" asp-action="SetToCart" asp-route-Id="@data.Id">Add to cart</a></td>
            </tr>
        }
    </tbody>
</table>

DeshanSLIIT/Views/Asset/TransferAction.cshtml
@model TransferDetails
@{
    ViewData["Title"] = "TransferAction";
}

<h1>TransferAction</h1>

<form method="post">
    <div class="row justify-content-center">
        <div  class="col-8">
            <div class="form-group">
              <lable for="txtLocation">Location</lable>
              <input type="text" placeholder="" class="form-control" id="txtLocation" asp-for="Location" required>
            </div>
            <div class="form-group">
                  <lable for="txtDetails">Category</lable>
                  @Html.DropDownListFor(model => model.CatData.CategoryType, ViewBag.CategoryList as SelectList, "--- Select ---", new {@class = "form-control"})
            </div>
            <p></p>
            <div class="form-group">
                <div class="col-2">
                    <button type="submit" class="btn btn-success" id="btnSave" asp-controller="Asset" asp-action="TransferAssets">Confirm</button>
                </div>      
            </div>
        </div>
    </div>
</form>

DeshanSLIIT/Views/Asset/TransferTable.cshtml
@model IEnumerable<Transfer>
@{
    ViewData["Title"] = "TransferTable";
}

<h1>TransferTable</h1>

<div class="col-3 my-3">
    <input type="text" class="form-control" list="datalist" onkeyup="ac(this.value)">
    <datalist id="datalist">
    </datalist>
</div>

<table class="table table-danger table-hover">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">TID</th>
          <th scope="col">CartID</th>
          <th scope="col">Name</th>
          <th scope="col">ISBN</th>
          <th scope="col">Location</th>
          <th scope="col">Date</th>
          <th scope="col">Category</th>
          <th scope="col">Print</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
              <th scope="row">@data.Id</th>
              <td>@data.TID</td>
              <td>@data.CartID</td>
              <td>@data.Name</td>
              <td>@data.ISBN</td>
              <td>@data.Location</td>
              <td>@data.Date</td>
              <td>@data.Category</td>
              <td><a type="button" class="btn btn-warning" asp-controller="Asset" asp-action="TransferTableByID" asp-route-Id="@data.TID">Print</a></td>
            </tr>
        }
    </tbody>
</table>

DeshanSLIIT/Views/Asset/TransferTableByID.cshtml
@model IEnumerable<Transfer>
@{
    ViewData["Title"] = "TransferTableByID";
}

<h1>TransferTableByID</h1>

<table class="table table-danger table-hover">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">TID</th>
          <th scope="col">CartID</th>
          <th scope="col">Name</th>
          <th scope="col">ISBN</th>
          <th scope="col">Location</th>
          <th scope="col">Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
              <th scope="row">@data.Id</th>
              <td>@data.TID</td>
              <td>@data.CartID</td>
              <td>@data.Name</td>
              <td>@data.ISBN</td>
              <td>@data.Location</td>
              <td>@data.Date</td>
            </tr>
        }
    </tbody>
</table>